#!/bin/sh

docker run \
  -e POSTGRES_USER=$INPUT_DB_USER \
  -e POSTGRES_PASSWORD=$INPUT_DB_PASSWORD \
  -e POSTGRES_DB=$INPUT_DB_NAME \
  -d -p 5432:5432 postgis/postgis:$INPUT_PSQL_VERSION-$INPUT_PSQL_VERSION
