name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - uses: SPalominos/PostGIS-Installer-Action@v0.0.3
      - name: Setup SDKs and run test
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 11.0.10-open
          sdk install groovy 3.0.7
          groovy test.groovy
